version: '3'

networks:
  service:
    driver: bridge
  exposer:
    driver: bridge
    internal: false

services:
  linux:
    build: ./portfolio-container
#   volumes: 
#    - ./portfolio-container/bash.bashrc:/home/visitor/.bashrc:ro
    networks:
      - service
  backend:
    build: ./portfolio-backend
    ports:
      - 8282:8282
    links:
      - linux
    depends_on:
      - linux
    networks:
      - service
      - exposer
  frontend:
    build: ./portfolio-frontend
    ports:
      - 1234:1234
    depends_on:
      - backend
    # links:
    #   - backend
    # networks:
    #   - service
  proxy:
    image: nginx:latest
    ports: 
     - 80:80
    volumes: 
     - ./portfolio-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
     - linux
     - backend
     - frontend
    # networks:
    # #  - service
    #  - exposer