version: '3.9'

services:
  linux:
    build: ./portfolio-container
    expose:
     - "22"
#   volumes: 
#    - ./portfolio-container/bash.bashrc:/home/visitor/.bashrc:ro
    networks:
     - service
  backend:
    build: ./portfolio-backend
    expose:
     - "8282"
    links:
     - linux
    depends_on:
     - linux
    networks:
     - service
  frontend:
    build: ./portfolio-frontend
    expose:
      - "1234"
    links:
      - backend
    depends_on:
     - backend
    networks:
     - service
  proxy:
    image: nginx:latest
    ports: 
     - 80:80
    volumes: 
     - ./portfolio-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
     - linux
     - backend
     - frontend
    networks:
     - service
     - exposer

networks:
  service:
    driver: bridge
    internal: true
  exposer:
    driver: bridge
    internal: false