version: '3.9'

services:
  linux:
    build: ./portfolio-container
    volumes: 
     - ./portfolio-container/bash.bashrc:/home/visitor/.bashrc:ro
    ports:
     - 22:22
  backend:
    build: ./portfolio-backend
    ports:
     - 8282:8282
    depends_on:
     - linux
    volumes_from:
     - linux
  frontend:
    build: ./portfolio-frontend
    ports:
     - 1234:1234
    environment:
      BACKEND_IP: backend
    depends_on:
     - backend
  proxy:
    image: nginx:latest
    ports: 
     - 80:80
    volumes: 
     - ./portfolio-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
     - backend
     - frontend
