version: '3'

services:
  linux:
    build: ./portfolio-container
    volumes: 
     - ./portfolio-container/bash.bashrc:/home/visitor/.bashrc:ro
    ports:
     - 22:22
  frontend:
    build: ./portfolio-frontend
    ports:
      - 1234:1234
    environment:
      BACKEND_IP: backend
    depends_on:
      - backend
  backend:
    build: ./portfolio-backend
    ports:
      - 8282:8282
    environment:
      CONTAINER_IP: linux
    depends_on:
      - linux
  proxy:
    image: nginx:latest
    ports: 
      - 80:80
    volumes: 
     - ./portfolio-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
     - frontend
     - backend
