version: '3.9'

services:
  linux:
    build: ./portfolio-container
    ports:
     - 22:22
#   volumes: 
#    - ./portfolio-container/bash.bashrc:/home/visitor/.bashrc:ro
  backend:
    build: ./portfolio-backend
    ports:
     - 8282:8282
    links:
     - linux
    depends_on:
     - linux
  frontend:
    build: ./portfolio-frontend
    ports:
     - 1234:1234
    depends_on:
     - backend
  proxy:
    image: nginx:latest
    ports: 
     - 80:80
    volumes: 
     - ./portfolio-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
     - linux
     - backend
     - frontend
